import streamlit as st

# ✅ All secrets loaded from Streamlit Cloud UI - never commit real values
SECRET_KEY = st.secrets["general"]["SECRET_KEY"]

# Branch to Sheet Name Mapping
BRANCH_SHEETS = {
    "TWMC LEYTE": "Sheet_Branch1",
    "TWMC SAMAR": "Sheet_Branch2",
    "TWMC CALBAYOG": "Sheet_Branch3",
    "TWMC SOUTHERN LEYTE": "Sheet_Branch4"
}

# ⚠️ USER DATABASE - For production, use a real database with hashed passwords
# Passwords shown as plaintext for demo - USE BCRYPT IN PRODUCTION!
USERS = {
    "admin": {"password": "admin123", "role": "admin", "branch": None},
    "mod1": {"password": "mod123", "role": "moderator", "branch": "TWMC LEYTE"},
    "mod2": {"password": "mod123", "role": "moderator", "branch": "TWMC SAMAR"},
    "mod3": {"password": "mod123", "role": "moderator", "branch": "TWMC CALBAYOG"},
    "mod4": {"password": "mod123", "role": "moderator", "branch": "TWMC SOUTHERN LEYTE"},
    "ley_fats": {"password": "fats123", "role": "encoder", "branch": "TWMC LEYTE", "team": "Fat's"},
    "ley_gfs": {"password": "gfs123", "role": "encoder", "branch": "TWMC LEYTE", "team": "Gfs"},
    "ley_dcat": {"password": "dcat123", "role": "encoder", "branch": "TWMC LEYTE", "team": "Dcat"},
    "sam_fats": {"password": "fats123", "role": "encoder", "branch": "TWMC SAMAR", "team": "Fat's"},
    "sam_gfs": {"password": "gfs123", "role": "encoder", "branch": "TWMC SAMAR", "team": "Gfs"},
    "sam_dcat": {"password": "dcat123", "role": "encoder", "branch": "TWMC SAMAR", "team": "Dcat"},
    "cal_fats": {"password": "fats123", "role": "encoder", "branch": "TWMC CALBAYOG", "team": "Fat's"},
    "cal_gfs": {"password": "gfs123", "role": "encoder", "branch": "TWMC CALBAYOG", "team": "Gfs"},
    "cal_dcat": {"password": "dcat123", "role": "encoder", "branch": "TWMC CALBAYOG", "team": "Dcat"},
    "sol_fats": {"password": "fats123", "role": "encoder", "branch": "TWMC SOUTHERN LEYTE", "team": "Fat's"},
    "sol_gfs": {"password": "gfs123", "role": "encoder", "branch": "TWMC SOUTHERN LEYTE", "team": "Gfs"},
    "sol_dcat": {"password": "dcat123", "role": "encoder", "branch": "TWMC SOUTHERN LEYTE", "team": "Dcat"},
}

# Google Sheets Configuration - ID loaded from secrets
GOOGLE_SHEET_ID = st.secrets["general"]["GOOGLE_SHEET_ID"]

# Product Database
PRODUCT_LIST = {
    "AMOXIL V": {"SACHET", "BOX"},
    "ELEC V": {"SACHET", "BOX"},
    "NOROVIT": {"10ML", "50ML", "100ML"},
    "PPG": {"SACHET", "BOX"},
    "FEATHERSHINE": {"SACHET", "BOX"},
    "WORM X": {"PAD", "BOX"},
    "WORM X MAXX": {"PAD", "BOX"},
    "-- OTHERS --": {},
    "DOXA-V": {"SACHET", "BOX", "KL", "PAD"},
    "PARA-V": {"SACHET", "BOX", "KL", "PAD"},
    "TRIMAX": {"SACHET", "BOX"},
    "MULTIMAX": {"SACHET", "BOX"},
    "ELECTROMAX": {"SACHET", "BOX"},
    "MULTIMAX D5": {"BOTTLE", "BOX"},
    "DOX-C-LIN GOLD": {"SACHET", "BOX"},
    "DOX-C-TRIN GOLD": {"SACHET", "BOX"},
    "IRON-VET": {"BOTTLE", "BOX"},
    "BULATIGOK SD": {"SACHET", "BOX"},
    "TRIFAST": {"SACHET", "BOX"},
    "ALAMYCIN LA": {"BOTTLE", "BOX"}
}

# Encoder Lists (per branch)
LEYTE_ENCODERS = {
        "ley_fats": {"BEN DADULA",
                  "GEE FERNAND RIÑOS",
                  "GLAIZA MAE BANTANOS",
                  "GREGORIO CABELTE JR.",
                  "JAIME PACAYDE",
                  "JAYVEE BAGUNAS",
                  "LEIGHMARK DAGOHOY",
                  "MELCHOR PALAJOREN",
                  "MARK WELL REI LAKE"},
        "ley_dcat" : {"LORRAINE ANGELA CABILIC"},
        "ley_gfs": {"LEONIL LIBY APOR"}
                  }

SAMAR_ENCODERS = {
        "sam_fats" : {"ALELOUR JABEGUERO",
                    "ARIEL OBILLO",
                    "ARISTEO ASI",
                    "CLETUS JOMAR PENEDA",
                    "DONALD CABO",
                    "JOHN LAWRENCE GUASIS",
                    "RALPH CARVAJAL",
                    "REDELON ABARRO",
                    "WENDYS LEGUA"},
        "sam_dcat" : {"JEREEY NAVIDAD",
                    "LOWELL LORENZO"},
        "sam_gfs" : {"LUIS DURAN"}
                }

CALBAYOG_ENCODERS = {
        "cal_fats" : {"ARCHIE CALUGCUGAN",
                    "DELDRINE GORDO",
                    "ELMER FUENTEBLANCA",
                    "JOEMAR ROTAMULA",
                    "JOMARI DOLON",
                    "MICHAEL ABLAZO",
                    "MICHAEL PANZO",
                    "ROBERT BALISBISAN"},
        "cal_dcat" : {"JASON CHIQUILLO"},
        "cal_gfs" : {"JAYSON ARANDIA"}
                    }

SOLEY_ENCODERS = {
        "sol_fats" : {"ALJHON INDIENTE",
                    "FELIX FRANCA",
                    "JAY KARL VERTUDAZO",
                    "JERWIN BATHAN",
                    "JONNEL PENE",
                    "JOVEN DEL ROSARIO",
                    "MIKE ANTHONY MIER",
                     "SANDY MARILLA"},
        "sol_dcat" : {"JUDEAH RUBILLOS"},
        "sol_gfs" : {"RUEL MENIABLE"}
                }

# LEYTE_ENCODERS = ["-- Full Name --",
#                   "BEN DADULA",
#                   "GEE RIÑOS",
#                   "GLAIZA MAE BANTANOS",
#                   "GREGORIO CABELTE JR.",
#                   "JAIME PACAYDE",
#                   "JAYVEE BAGUNAS",
#                   "LEIGHMARK DAGOHOY",
#                   "MELCHOR PALAJOREN",
#                   "LORRAINE ANGELA CABILIC",
#                   "LEONIL LIBY APOR"
#                   ]

# SAMAR_ENCODERS = ["-- Full Name --",
#                   "ALELOUR JABEGUERO",
#                   "ARIEL OBILLO",
#                   "ARISTEO ASI",
#                   "CLETUS JOMAR PENEDA",
#                   "DONALD CABO",
#                   "JOHN LAWRENCE GUASIS",
#                   "RALPH CARVAJAL",
#                   "REDELON ABARRO",
#                   "WENDYS LEGUA",
#                   "JEREEY NAVIDAD",
#                   "LOWELL LORENZO",
#                   "LUIS DURAN"]

# CALBAYOG_ENCODERS = ["-- Full Name --",
#                   "ARCHIE CALUGCUGAN",
#                   "DELDRINE GORDO",
#                   "ELMER FUENTEBLANCA",
#                   "JOEMAR ROTAMULA",
#                   "JOMARI DOLON",
#                   "MICHAEL ABLAZO",
#                   "MICHAEL PANZO",
#                   "ROBERT BALISBISAN",
#                   "JASON CHIQUILLO",
#                   "JAYSON ARANDIA"]

# SOLEY_ENCODERS = ["-- Full Name --",
#                   "ALJHON INDIENTE",
#                   "FELIX FRANCA",
#                   "J CARL VERTUDAZO",
#                   "JERWIN BATHAN",
#                   "JONNEL PENE",
#                   "JOVEN DEL ROSARIO",
#                   "MIKE ANTHONY MIER",
#                   "SANDY MORILLA",
#                   "RUEL MENIABLE"]

# Customer Lists (trimmed for brevity - keep your full lists)
LEYTE_CUSTOMERS = ["-- Select Customer --",
                   "3 KING'S AGRIVET SUPPLIES",
                   "4J'S AGRIVET TRADING",
                   "4R'S STORE",
                   "5M AGRIVET",
                   "A & G BERCERO AGRIVET",
                   "A & J AGRIVET SUPPLY",
                   "A & N AGRIVET SUPPLY",
                   "A.I.R. AGRIVET SUPPLY",
                   "A-1 MILLING CORPORATION - (TIRES)",
                   "A1-MILLING",
                   "AB FARMERS AGRIVET SUPPLY",
                   "ACF AGRIVET",
                   "AGRIVET KO",
                   "AILEEN'S STORE",
                   "AJ BORNE AGRIVET SUPPLY",
                   "AKIO'S AGRIVET SUPPLY",
                   "ALARIC AGULLO",
                   "ALICANDO VARIETY",
                   "ALICE ARIAS",
                   "ALRENCE AGRIVET TRADING",
                   "ANGELO VICENTE",
                   "ANTONI'S AGRIVET SUPPLY",
                   "ARNEL BOSTILLO",
                   "ARTURO BERINGUEL",
                   "ATN AGRIVET SUPPLY",
                   "B AND E AGRIVET SUPPLY & VETERINARY SERVICES",
                   "BAKALA AGRIVET",
                   "BELEN STORE",
                   "BEN ANTHONY DADULA",
                   "BENJIE SARI-SARI STORE",
                   "BENSOI STORE",
                   "BGT AGRIVET - ALANG ALANG",
                   "BGT AGRIVET - PALO",
                   "BLAYNE AGRIVET SUPPLY",
                   "BLUE-CROSS VETERINARY CLINIC (AHPC)",
                   "C AND J AGRIVET TRADING",
                   "CALIX YANSY VARIETY STORE",
                   "CHERRY'S STORE",
                   "CIANYANA AGRIVET TRADING",
                   "CLARIDAD AGRIVET SUPPLY",
                   "CONCEPTION RELEVO",
                   "CULASIAN AGRIVET AND SUPPLIES",
                   "CUTA FARMERS MULTI COOP",
                   "D & E AGRIVET SUPPLY",
                   "DEMAND CREATION - GEE RINOS",
                   "DEMAND CREATION - JAYVEE BAGUNAS",
                   "DEMAND CREATION - LEONEL LIBY APOR",
                   "DEMAND CREATION - RECHIE APOR",
                   "DEMAND CREATION ACTIVITY - LEYTE 1",
                   "DENCIANG'S STORE",
                   "DINA DANDAN",
                   "DINA ROSENAS",
                   "DJ CONCRETE SOLUTIONS, INC. - (TIRES)",
                   "DODONG TORENO",
                   "DOMINGO SARI-SARI STORE",
                   "E & R AGRIVET SUPPLIES",
                   "E & V ARGUTA'S ENTERPRISES",
                   "E&E LOPEZ AGRI SUPPLY",
                   "EDGAR DAGANASOL",
                   "EIVERJ LHANZ STORE",
                   "ELEGIO R. BERSALES",
                   "FELIMON BAGUE",
                   "FRANCIS STORE",
                   "FURPETS PET SALON (AHPC)",
                   "GASPAR CUAYZON",
                   "GCP ASTORGA GENERAL MERCHANDISE",
                   "GEMINI AGRIVET",
                   "GIL P. REBATO/ONJIE AGRIVET",
                   "GIMA'S MKTG.",
                   "GIRLEY TAN SANICO",
                   "GLADYS VENEZUELA",
                   "GLD TRUCKING",
                   "GLD TRUCKING & HAULING SERVICES - (TIRES)",
                   "GOLDEN J5 GAMEFARM",
                   "GOLDEN RIVER ENTERPRISES - (TIRES)",
                   "GOLS AGRI TRADING",
                   "GV VARIETY STORE",
                   "HAPPY TAILS AGRIVET SUPPLY",
                   "IDAY AGRIVET",
                   "J & A AGRIVET",
                   "JASON STORE",
                   "JAZZ ENTERPRISE",
                   "JENNY'S AGRIVET TRADING",
                   "JERICO MALINDOG",
                   "JETH ALTON BERINO",
                   "JIG AGRIVET SUPPLY",
                   "J'MARK AGRIVET",
                   "JOHN JACOB SARI-SARI STORE",
                   "JOSE O. CALISEN",
                   "JOSEF YUCAMCO",
                   "JOSEPH CLINT M. MALQUISTO",
                   "JOY/JEFFREY STORE",
                   "JP STORE-LEYTE",
                   "JUN ZABALA (AHPC)",
                   "JUPITER DISTRIBUTION INC. - (TIRES)",
                   "JVT AGRIVET",
                   "KAE & K VARIETY STORE",
                   "KALANTAS ENTERPRISES",
                   "KAREN'S AGRIVET SUPPLY",
                   "KATRIZA STORE",
                   "KAYZEIL L. BRITENIA",
                   "KENNETH A. DELLORO",
                   "KENNETH MORFE",
                   "KER'S AGRIVET TRADING",
                   "KIM JAID AGRIVET",
                   "KING JUMONG AGRIVET SUPPLY",
                   "KNJ AGRIVET SUPPLY",
                   "KYRIC AGRIVET SUPPLY",
                   "LESTER LPG TRADING",
                   "LIEZEL STORE",
                   "LINA BARRIENTOS",
                   "LLOYD NOVILLA",
                   "LUCKY 3 STORE LIBERTAD",
                   "MAIDEN'S AGRIVET SUPPLY",
                   "MANOY AND CAYONG AGRIVET SUPPLY",
                   "MARVIN VELARDE/MC PANIS STORE",
                   "MATHEW AND JOHN ENTERPRISES",
                   "MAXENE V. AGRIVET TRADING",
                   "MC AGRIVET SUPPLY",
                   "MJ AGRIVET",
                   "MOLABOLA STORE",
                   "MRV2 AGRIVET TRADING",
                   "NIEL AND DEM ENTERPRISES",
                   "NITROPLUS AUTO CARE SERVICES - (TIRES)",
                   "NO WHELL AGRIVET SUPPLY",
                   "NOEL PALANCA",
                   "NOGAL STORE",
                   "NOLERS STORE",
                   "NSN AGRICULTURAL SUPPLY",
                   "ORLY STORE",
                   "OSCAR GALVEZ",
                   "PACIFICA AGRIVET SUPPLIES INC. - CARIGARA",
                   "PACIFICA AGRIVET SUPPLIES, INC. - ABUYOG",
                   "PACIFICA AGRIVET SUPPLIES, INC. - BURGOS I",
                   "PACIFICA AGRIVET SUPPLIES, INC. - BURGOS II",
                   "PACIFICA AGRIVET SUPPLIES, INC. - PALO",
                   "PACIFICA AGRIVET SUPPLIES, INC. - RIZAL TACLOBAN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - TACLOBAN PORT AREA",
                   "PACIFICA AGRIVET SUPPLIES, INC. - TORRES",
                   "PAWS AND CLAWS",
                   "PET HAVEN VETERINARY CLINIC - SAN JOSE (AHPC)",
                   "PETSENSE PET SUPPLIES & ACCESSORIES SHOP (AHPC)",
                   "PINKYS AGRIVET",
                   "PIOBETH STORE",
                   "PLACEMENT CAMPAIGN (FOR SAMPLING ) - LEYTE",
                   "POSING AGRIVET/VILMA CABRERA",
                   "PRINCESS STORE",
                   "RAISER'S MARKETING",
                   "RBD GAMEFARM",
                   "RDA AGRIVET SUPPLY",
                   "REAS",
                   "RENE LAMPAYAN",
                   "RENIK AGRIVET",
                   "RICO C. MAGHINAY",
                   "RITEMEAT MARKETING - (TIRES)",
                   "RJIR ENTERPRISES CORP. - (TIRES)",
                   "RJS AGRIVET",
                   "ROGELIO COSTIN",
                   "ROLENE ENTERPRISES",
                   "ROSIES MINI MART",
                   "ROWENA AGRI SUPPLY",
                   "ROYAL EMPYREAN BREEDER",
                   "RRD-6 AGRIVET SUPPLY",
                   "SAMS TRADING",
                   "SAN LORENZO STORE",
                   "SETOSTA POULTRY FARM",
                   "SIAPOL AGRIVET SUPPLY",
                   "SMR VETERINARY CLINIC AND PET SUPPLIES (AHPC)",
                   "SOLAMO ENTERPRISES",
                   "SP STORE",
                   "SPARTANS GAMEFARM",
                   "ST. BENEDICT VETERINARY SERVICES & CONSILTANCY (AHPC)",
                   "ST. JUDE-CVE AGRICULTURAL MARKETING CORPORATION",
                   "ST. MATTHEW AGRI TRADING",
                   "SYLVIA'S VARIETY STORE",
                   "TANASYO AGRIVET",
                   "TARANTULA GAMEFARM",
                   "TESS ARIZA",
                   "THUNDER AGRIVET - LEYTE",
                   "TICK-TOCK MINIMART",
                   "TINDAHAN NI ANOK",
                   "TINDAHAN NI MA'AM GRACE",
                   "TWMC TAC LEYTE - (TIRES)",
                   "UMAHAN AGRIVET SUPPLY",
                   "VERSE STORE",
                   "VISPET DEVELOPMENT CORPORATION - (TIRES)",
                   "WALK-IN - LEYTE",
                   "WAYNESTAR KENNEL.PH (AHPC)",
                   "WENIE'S ENTERPRISE",
                   "WHOZHAI TRADING",
                   "WILSON UY",
                   "WRH",
                   "WVN AGRIVET SUPPLY",
                   "YSAY'S AGRIVET",
                   "ZENAIDA VERECIO"]

SAMAR_CUSTOMERS = ["-- Select Customer --",
                   "3-KIM STORE",
                   "A & Z CONSUMER GOOD TRADING",
                   "A.C. ADVINCULA BUILDERS AND SUPPLY",
                   "AAD WARRIORS GAME FARM",
                   "ABA10 AGRIBIZ",
                   "ACABAN STORE",
                   "ADRIAN ROBIENE",
                   "AGPRO AGRIVET SUPPLY",
                   "AGRI-DOK AGRIVET SUPPLY",
                   "ALBERT A. DACUTAN",
                   "ALLYSA'S AGRIVET SUPPLY",
                   "ALMA AGRIVET SUPPLY",
                   "AMEA AGRIVET SUPPY",
                   "AMLL AGRIVET SUPPLY",
                   "ANALIZA'S WET & DRY GOODS STORE",
                   "ARAZA",
                   "ARCHIE CASPE",
                   "ARJOHN AGRIVET SUPPLY",
                   "BABES MEATSHOP",
                   "BARBETH'S BAKESHOP",
                   "BOB STORE",
                   "BOBBY TABUNAN",
                   "BRILLIANT STORE",
                   "BUENA'S HARDWARE AND CONSTRUCTION SUPPLY",
                   "CANDALA AGRIVET SUPPLY",
                   "CATHY STORE",
                   "CHONA'S STORE",
                   "CLC AGRIVET",
                   "COCOY AGRIVET SUPPLIES",
                   "CONCEPCION BABON STORE",
                   "CUPID'S TRADING - (TIRES)",
                   "CUPIDS-BURAY",
                   "DARAS STORE",
                   "DENNIS EVARDONE",
                   "DOLRICH AGRIVET SUPPLY",
                   "DONGALLO ,MA. CRISTINA",
                   "E & E LOPEZ-SEZO AGRIVET SUPPLY",
                   "ECO SAVERS GROUP VENTURES INC. - (TIRES)",
                   "EDENCIO A. AFABLE",
                   "EDITA ELARDO EVARDONE",
                   "EDSEL D. MANOCAY",
                   "EDWIN NACOR",
                   "ETAN CONSTRUCTION - (TIRES)",
                   "FALCO AGRIVET SUPPLY",
                   "FARMERS AGRIVET",
                   "FELISA'S CONSUMER GOODS TRADING",
                   "FLORO CUI OROCAY",
                   "FLORO YAPE",
                   "GABITO AGRIVET",
                   "GEMS STORE",
                   "GGF MT. DANGLAY",
                   "GLENDA CALZADO",
                   "GOLDEN NUGGETS FOOD VENTURES CORP - (TIRES)",
                   "GRACE P. LUTERIA",
                   "GRANULETTE AGRIVET SUPPLIES",
                   "H & M AGRIVET SUPPLY",
                   "HADJI GUNDA",
                   "HILDA C. NAVIDAD",
                   "J & A RICE-RETAIL AND CONVENIENCE STORE",
                   "J & A STORE",
                   "J & E VENTURES CORPORATION",
                   "J & R GENERAL ENTERPRISE",
                   "JED STORE",
                   "JENNIFER FEEDS STORE",
                   "JENNIFER GELLI",
                   "JEPOY STORE",
                   "JHON-JHON ALDE",
                   "JHONLYN STORE",
                   "JIMMY NAVES",
                   "JM STORE",
                   "JOHNNY ELPIDES",
                   "JONEL BAYSA",
                   "JOSA BITUIN SALICSIC",
                   "JOSELITO NAVIDAD",
                   "JOSEPHINE D. BAYARONG",
                   "JOSIE STORE",
                   "JOVELYN STORE",
                   "JOY DADULLA",
                   "JRC SQUARE",
                   "JUL BAKUN (TIRES)",
                   "JUNCEL'S PET SHOP",
                   "JYLL AGRIVET SUPPLY",
                   "KAC AGRIVET",
                   "KAN INAY AGRIVET SUPPLY",
                   "KAREN GRACE SARI-SARI STORE",
                   "KARENJOY AGRIVET SUPPLY",
                   "KATE'S STORE",
                   "KFC",
                   "KIMDREY'S HOG FARM",
                   "KLOEHS STORE",
                   "KYLEPOT AGRIVET SUPPLY",
                   "LEIGH YNNA'S STORE",
                   "LEORANDY RAPADA",
                   "LESTER YHAN SARI-SARI STORE",
                   "LEV-YAN AGRIVET SUPPLY",
                   "LGC STORE",
                   "LHARJEST K ENTERPRISES",
                   "LIBAS AGRARIAN REPORT BENEFICIARY ASSO. (LARBA)",
                   "LOPE TY",
                   "LORENZ FARM",
                   "LORIEJANE M. ELACION",
                   "LOY YAPE",
                   "LUIS A. DURAN",
                   "LUZ BAQUE",
                   "MAGU FARM",
                   "MANUKANG BAYAN - RIVERSIDE SULAT",
                   "MANUKANG BAYANG STA. RITA",
                   "MARITES RAMIREZ",
                   "MERCY SARI-SARI STORE",
                   "MER-ENESSA STORE",
                   "MICHANG AGRIVET SUPPLY",
                   "MIKEY ABAIGAR",
                   "MILAGROS JAMEELA D. KHAN",
                   "MILLENIUM - BORONGAN",
                   "MNW SARI-SARI STORE",
                   "MTC STORE",
                   "NABLE'S AGRIVET",
                   "NACUA AGRIVET SUPPLY",
                   "NHORRANE SARI-SARI STORE",
                   "NOLITO P. OLPATO",
                   "OFELIA STORE",
                   "OLYMPIO D. DEMILLO",
                   "PACIFICA AGRIVET SUPPLIES, INC. -  SAN FRANCISCO",
                   "PACIFICA AGRIVET SUPPLIES, INC. - ALLEN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - BARTOLOME",
                   "PACIFICA AGRIVET SUPPLIES, INC. - CALBIGA",
                   "PACIFICA AGRIVET SUPPLIES, INC. - DOLORES",
                   "PACIFICA AGRIVET SUPPLIES, INC. - LIMBAUAN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - ORAS",
                   "PACIFICA AGRIVET SUPPLIES, INC. - SAN JUAN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - SAN NICHOLAS",
                   "PACIFICA AGRIVET SUPPLIES, INC. - SAN ROQUE",
                   "PATER ASERIOS",
                   "PAUL PACUANCUAN",
                   "PAZ WHITE",
                   "PRESCIOUS DEVINE STORE",
                   "R.M.O STORE",
                   "RACQUEL R. GLORIA",
                   "RAUL MACASA",
                   "RECHY S. AYHON",
                   "RENE P. SABANAL JR.",
                   "REXAN QUEJADA",
                   "REYNALDO GONZALES",
                   "RIC MACAMAY",
                   "RICHARD MENIANO",
                   "RL AGRIVET TRADING",
                   "RODMAR TRUELDA",
                   "ROEL BACCARA",
                   "ROGELIO CORTAVISTA",
                   "ROGELIO STORE",
                   "ROMY CABANATAN",
                   "RONAN BABON",
                   "ROSALIA QUIRANTE BALDO",
                   "RUFRANCE - QUINAPONDAN",
                   "RYAN ADEL",
                   "SALVA GAGATIGA",
                   "SAM HOG AND POULTRY SUPPLIES",
                   "SAMAR WHITE ROCK - (TIRES)",
                   "SANDRA C. DELA ROSA",
                   "SBSP BREEDERS CLUB - SAMAR 1",
                   "SELDE FARM",
                   "SHAHANIE",
                   "SHARLET E. NAVARRO",
                   "SILAS TOMILLOSO",
                   "SIRANG VETERINARY CLINIC (AHPC)",
                   "SOLLANO'S GENERAL MERCHANDISE",
                   "SYLVIA AGRI PRODUCTS",
                   "TABI RICE PLANTER ASSOCIATION",
                   "TACLOBAN WINNER MKTG CORP/MELANIE TAGAPAN",
                   "TACLOBAN WINNER MKTG CORP/NILDA SANTOS",
                   "TAYON STORE",
                   "THIRDY FEEDS",
                   "THOMAS JATAAS",
                   "TOM & JELMA AGRI",
                   "TONYO'S MEATSHOP",
                   "TRIPLE J POULTRY SUPPLY",
                   "VINICE AGRIVET SUPPLY",
                   "WELITO CAJEPE",
                   "WYNNZY AGRIVET SUPPLY",
                   "YIEL BORJA",
                   "ZALDY",
                   "ZANDRA AGRIVET SUPPLY"]

CALBAYOG_CUSTOMERS = ["-- Select Customer --",
                      "AG'S FARM",
                      "ALMA'S STORE",
                      "AMADO ADVINCULA",
                      "ANTONIETTE SHE FEEDS & RICE RETAILER",
                      "ANZYL POCHE",
                      "ARCV TRADING",
                      "BARANGAY SAN VICENTE FARMERS ASSOCIATION",
                      "BRIAN RIVERA",
                      "BUSAY FARM",
                      "CHUBBS",
                      "CITY VETERINARY OFFICE",
                      "COSMOD AGRIVENTURES",
                      "CRECOO RICE & FEEDS RETAILER",
                      "CRV AGRIVET SUPPLY",
                      "CUEVAS AGRIVET SUPPLY",
                      "E & N CHICKEN BROILER FARM",
                      "ED DEN'S AGRIVET SUPPLY",
                      "ELMER FARM",
                      "ELMER LOGERO FUENTEBLANCA",
                      "ELYONG'S LIVESTOCK FARM",
                      "EPOY STORE",
                      "ESMER STORE",
                      "FMB LIVESTOCK, POULTRY & MINI DRESSING PLANT",
                      "GAV'Z AGRIVET SUPPLY",
                      "GREGORIO FARM",
                      "HBE PET CLINIC",
                      "ILOSO'S MINI STORE",
                      "IVY STORE",
                      "JAD STORE",
                      "JAS FEED SUPPLY",
                      "JAYSON B. ARANDIA",
                      "JC STORE",
                      "JD SCHOOL & OFFICE SUPPLIES TRADING",
                      "JJ AGRIVET SUPPLY",
                      "JMN MINI AGRIVET",
                      "JOEL AGRIVET SUPPLY",
                      "JOKER 182 GAMEFARM & AGRIVET SUPPLY",
                      "JR AGUILAR",
                      "JUSTJANE PET FOOD STORE",
                      "KAREN AGRIVET",
                      "KIRK NAKILA VENTURES",
                      "LABENIA VARIETY STORE",
                      "LAVEZARES HOG RAISERS ASSOCIATION, INC",
                      "LILLIA STORE",
                      "LLUZ LAYER FARM",
                      "LUCERO RICE MILL",
                      "MAHINAY STORE",
                      "MAMA LOVE'S DM & JDC",
                      "MANGUINOO HOG FARMER'S ASSOCIATION",
                      "MARIDEL SARI SARI STORE",
                      "MERLY VARIETY STORE",
                      "MERLYN STORE",
                      "MILLENIUM AGRI RAISER SUPPLY INC.",
                      "NANCY STORE",
                      "NAN'S FARM",
                      "NERIA N. IGUIRON STORE",
                      "NOAH AGRIVET SUPPLY",
                      "OBET AGRI-FEEDS",
                      "OLIVERIO AGRIVET SUPPLIES",
                      "OVOY'S STORE",
                      "P & F BANTILO FARM",
                      "P A STRONG HOLD GAMEFARM",
                      "PACIFICA AGRIVET SUPPLIES, INC. - ALEGRIA",
                      "PACIFICA AGRIVET SUPPLIES, INC. - ALLEN N. SAMAR",
                      "PACIFICA AGRIVET SUPPLIES, INC. - DELPILAR OD 105",
                      "PACIFICA AGRIVET SUPPLIES, INC. - GANDARA",
                      "PACIFICA AGRIVET SUPPLIES, INC. - GOMEZ",
                      "PACIFICA AGRIVET SUPPLIES, INC. - MARCOS OD 105",
                      "PACIFICA AGRIVET SUPPLIES, INC. - NAVARRO",
                      "PACIFICA AGRIVET SUPPLIES, INC. - OBRERO",
                      "PACIFICA AGRIVET SUPPLIES, INC. - RAWIS",
                      "PAMBEGING STORE",
                      "PIT MASTER'S AGRIVET SUPPLY",
                      "POTY",
                      "PV & F VARIETY STORE",
                      "R & S PIG FARM",
                      "RAMON TUBALLAS",
                      "RAPRAP STORE",
                      "REGGIE MORILLO",
                      "ROBERT STORE",
                      "RODOLFO B. ALEMAÑA",
                      "RUBY STORE",
                      "RUNIL MILA",
                      "RUTH'S STORE",
                      "SANDOVAL FARM",
                      "SAREG AGRIVET",
                      "SENIA STORE",
                      "SHADOY AGRIVET",
                      "SHANTELLE STORE",
                      "SILVIA LACATANGO",
                      "TACLOBAN WINNER MARKETING CORP (CALBAYOG)",
                      "VICENTE B. BOHOL",
                      "VINEYARD AGRIVET",
                      "WG AGRIVET",
                      "ZHYE FARMERS FEEDS"
                      ]

SOLEY_CUSTOMERS = ["-- Select Customer --",
                   "2DEN STORE",
                   "2K RICE AND FEEDS RETAILING",
                   "3H AGRIVET - SOGOD",
                   "3'S MARIAS VARIETY STORE",
                   "4MS AGRIVET SUPPLY",
                   "4MS AGRIVET SUPPLY - HINUNANGAN",
                   "ACM AGRIVET",
                   "ADELFA AGRIVET-HINUNDAYAN",
                   "ADELFA GARRY AGRIVET SUPPLY",
                   "AILEENN L. MENIABLE",
                   "AJV AGRIVET SUPPLY",
                   "AL JHON INGENTE",
                   "ALLEN STORE",
                   "ALVIN BOHOL FARM",
                   "ANGEL JR STORE",
                   "ARANGKADA STORE",
                   "ARGIE DALAPO FARM",
                   "ATTY.LAURO ALBON FARM",
                   "AURORA GLORIA",
                   "AYA STORE",
                   "B&L RICE AND FEEDS RETAILING",
                   "BABES MEATSHOP",
                   "BARKS N PURRS ANIMAL CLINIC",
                   "BB & M STORE",
                   "BEDA'S STORE",
                   "BIGBOY AGRIVET",
                   "BMA AGRIVET SUPPLY",
                   "BNLF STORE",
                   "BOBOY BORLAGDAN FARM",
                   "BORDS AGRIVET",
                   "BRAGA STORE",
                   "C5 AGRIVET SUPPLIES",
                   "CABALI-AN AGRIVET SUPPLY",
                   "CITY HUNTER",
                   "CLMD STORE",
                   "DANILO VELTRAN",
                   "DANTE PERE",
                   "DEDOT STORE",
                   "DENNA Q. PO",
                   "D'FARMERS AGRIVET",
                   "DONS FARM",
                   "DULCE AGRIVET",
                   "EC ADELFA AGRIVET",
                   "ELVIRA CABAÑA",
                   "ESQUENA STORE",
                   "EVELINA MONTALBAN",
                   "FEEDMINIA",
                   "FELIPE ZARATE FARM",
                   "FLOR LARUYA FARM",
                   "FLV GAMEFARM",
                   "FRANCESCO VETERINARY CLINIC (AHPC)",
                   "FRANCIS DACERA FARM",
                   "GEMSON AGRIVET",
                   "GEORGINA AGRIVET",
                   "GIELA ORACION",
                   "GM GABISAN",
                   "GT FARMERS",
                   "GT NORTHROP GAMEFARM",
                   "HENRY VILBAR FARM",
                   "HINUNDAYAN AGRIVET",
                   "IONNYX FEED SUPPLY",
                   "J- AGRIVET SUPPLY",
                   "J&M VARIETY STORE",
                   "JANUYAN CONSUMER GOODS TRADING",
                   "JE-ANN STORE",
                   "JEANNIVER BALBON FARM",
                   "JERWIN BATHAN",
                   "JHANIEVIEL STORE&AGRI SUPPLY",
                   "JHOVON AGRIVET-BATO",
                   "JHYLL'S FARM",
                   "JJ AGRIVET SUPPLY",
                   "JMP AGRIVET",
                   "JOESAL JOHN DEPLOMO FARM",
                   "JOHN GERALD",
                   "JOVEN DEL ROSARIO",
                   "JOY STORE- TOMAS OPPUS",
                   "JP AND S A AGRIVET",
                   "JP STORE",
                   "JR & MAI VARIETY STORE",
                   "JRP & 4KS AGRIVET SUPPLY",
                   "JUBETH VILLEGAS",
                   "JUDEA ROA RUBILLOS",
                   "JUDITH & GEROM STORE",
                   "JUNNEL PENE",
                   "KENEL DJ",
                   "LAMP COOP- LIBAGON",
                   "LPF FARM",
                   "LUCKY NINE",
                   "MAFA",
                   "MANEL RICE AND FEEDS STORE",
                   "MARANGOG AGRI TRADERS SLP ASSOCATION",
                   "MARCO'S STORE",
                   "MC AGRIVET",
                   "MGF AGRIVET SUPPLY",
                   "MIKE ANTHONY MIER",
                   "MILDRED AVELLANA BERRAME",
                   "MILLENIUM AGRI RAISERS SUPPLY, INC",
                   "MILLENNIUM AGRIVET - MAASIN",
                   "MMV SARI-SARI STORE",
                   "MOMAR A. CAHEPRE FARM",
                   "NENE'S FARM HOGS AND LAYER",
                   "NIDDELIN VILLAGRACIA FARM",
                   "NVC STORE",
                   "OTIKON COOP",
                   "PACIFICA AGRIVET SUPPLIES, INC. - BATO",
                   "PACIFICA AGRIVET SUPPLIES, INC. - CONCEPCION, SOGOD",
                   "PACIFICA AGRIVET SUPPLIES, INC. - HILONGOS",
                   "PACIFICA AGRIVET SUPPLIES, INC. - HINUNANGAN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - MAASIN",
                   "PACIFICA AGRIVET SUPPLIES, INC. - MAGSAYSAY, BAYBAY",
                   "PACIFICA AGRIVET SUPPLIES, INC. - OSMEÑA, SOGOD",
                   "PACIFICA AGRIVET SUPPLIES, INC. - RIZAL, BOULEVARD, BAYBAY",
                   "PAL & OCON GROCERY STORE",
                   "PAT GEN. MDSE.",
                   "PATROCENIO SARONA",
                   "PAUL AZ VARIETY STORE",
                   "PAWLERMO VET CLINIC (AHPC)",
                   "POWERTONE",
                   "R. YAN GAMEFARM",
                   "RANDEE AGRIVET",
                   "REM AGRIVET SUPPLY",
                   "RENA GRACE STORE",
                   "RESUS STORE",
                   "REYNANTE MONTEDERAMOS",
                   "RLB MERCHANDISE",
                   "RLB STELLBIRD",
                   "ROGELIO YAN FARM",
                   "ROLAND ESCOL",
                   "ROMAS AGRIVET",
                   "RON MAR AGRIVET SUPPLY",
                   "RONNIE DARGANTES",
                   "RUEL MENIABLE",
                   "RYAN CARLO SUNER",
                   "SABING STORE",
                   "SANDY  D. MARILLA",
                   "SARABIA STORE",
                   "SEBGREY'S AGRIVET",
                   "SHI-NA AGRIVET",
                   "SJ STORE",
                   "SN AGRIVET",
                   "SOUTHERN VETERINARY CLINIC (AHPC)",
                   "SUMMER SKY GAMEFARM",
                   "SYLVIA MACABUHAY FARM",
                   "TEFFANY ANN SUICO",
                   "TIGBAO COOP",
                   "TING2X STORE",
                   "TRIGO STORE",
                   "TRIPLE REY",
                   "TRIPLE Z STORE",
                   "VERGILIO PARAYNO FARM",
                   "VETMED SUPPORT - SOGOD",
                   "VICTORY AGRIVET SUPPLY",
                   "WING MERCHANDISE",
                   "XAVIER AGRIVET SUPPLY",
                   "YOLANDA RABANOS FARM",
                   "ZAI AND RAY AGRIVET SUPPLIES",
                   "ZIANA AGRIVET SUPPLY"
                   ]
